# This file was generated by GoReleaser. DO NOT EDIT.
class Execr < Formula
  desc "Keep obscured secrets alongside plaintext"
  homepage ""
  url "https://github.com/dhoelle/execr/releases/download/v0.1.1/execr_0.1.1_Darwin_x86_64.tar.gz"
  version "0.1.1"
  sha256 "4ead61c5bc5de270cb1136b4e1a91e6e7daca05c674ad26010b2c1da1e13fc8e"

  def install
    bin.install "execr"
  end
end
