# This file was generated by GoReleaser. DO NOT EDIT.
class Execr < Formula
  desc "Keep obscured secrets alongside plaintext"
  homepage ""
  url "https://github.com/dhoelle/execr/releases/download/v0.1.0/execr_0.1.0_Darwin_x86_64.tar.gz"
  version "0.1.0"
  sha256 "0641b60a8f2835b27d775014482f6de3b8e710c606ee92c5865bc585c6ffde29"

  def install
    bin.install "execr"
  end
end
