# This file was generated by GoReleaser. DO NOT EDIT.
class Execr < Formula
  desc "Keep obscured secrets alongside plaintext"
  homepage ""
  url "https://github.com/dhoelle/execr/releases/download/v0.1.1/execr_0.1.1_Darwin_x86_64.tar.gz"
  version "0.1.1"
  sha256 "f45b1dc28a7f516be3ea4abfcad77d05c85ed4d75b4dd02661f8efb7324dfc7b"

  def install
    bin.install "execr"
  end
end
