# This file was generated by GoReleaser. DO NOT EDIT.
class Redactr < Formula
  desc "Keep obscured secrets alongside plaintext"
  homepage ""
  url "https://github.com/dhoelle/redactr/releases/download/v0.1.15/redactr_0.1.15_Darwin_x86_64.tar.gz"
  version "0.1.15"
  sha256 "45ed93848af9bb0eef48e25b88124e59012b7efacef3c224721197ee70973bbb"

  def install
    bin.install "redactr"
  end
end
