# This file was generated by GoReleaser. DO NOT EDIT.
class Redactr < Formula
  desc "Keep obscured secrets alongside plaintext"
  homepage ""
  url "https://github.com/dhoelle/redactr/releases/download/v0.1.14/redactr_0.1.14_Darwin_x86_64.tar.gz"
  version "0.1.14"
  sha256 "e68ae8d4663a59dfdda12e18d023db7d2ead5f73147eaf68369b6472f9d49bd0"

  def install
    bin.install "redactr"
  end
end
